### ISSUE TITLE
Build error: WASM_BUILD_TOOLCHAIN=nightly-2020-10-05 cargo build --release

### ISSUE THREAD

**Issue by truedat101** [substrate-developer-hub/substrate-enterprise-sample#86]
When doing a first time install

(OS X M1 Mac)
- WASM_BUILD_TOOLCHAIN=nightly-2020-10-05 cargo build --release

```

error[E0282]: type annotations needed
    --> /Users/dkords/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-arithmetic-2.0.0/src/fixed_point.rs:541:9
     |
541  |                   let accuracy = P::ACCURACY.saturated_into();
     |                       ^^^^^^^^ consider giving `accuracy` a type
...
1595 | / implement_fixed!(
1596 | |     FixedI64,
1597 | |     test_fixed_i64,
1598 | |     i64,
...    |
1601 | |     "_Fixed Point 64 bits signed, range = [-9223372036.854775808, 9223372036.854775807]_",
1602 | | );
     | |__- in this macro invocation
     |
     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0282]: type annotations needed
    --> /Users/dkords/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-arithmetic-2.0.0/src/fixed_point.rs:541:9
     |
541  |                   let accuracy = P::ACCURACY.saturated_into();
     |                       ^^^^^^^^ consider giving `accuracy` a type
...
1604 | / implement_fixed!(
1605 | |     FixedI128,
1606 | |     test_fixed_i128,
1607 | |     i128,
...    |
1611 | |         [-170141183460469231731.687303715884105728, 170141183460469231731.687303715884105727]_",
1612 | | );
     | |__- in this macro invocation
     |
     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0282]: type annotations needed
    --> /Users/dkords/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-arithmetic-2.0.0/src/fixed_point.rs:541:9
     |
541  |                   let accuracy = P::ACCURACY.saturated_into();
     |                       ^^^^^^^^ consider giving `accuracy` a type
...
1614 | / implement_fixed!(
1615 | |     FixedU128,
1616 | |     test_fixed_u128,
1617 | |     u128,
...    |
1621 | |         [0.000000000000000000, 340282366920938463463.374607431768211455]_",
1622 | | );
     | |__- in this macro invocation
     |
     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0282`.
error: could not compile `sp-arithmetic`

```

**Comment by NukeManDan** [comment]
OS X M1 Mac is likely at least some of the problem, see here for tips (it doesn't play nice unfortunately): 
- https://github.com/substrate-developer-hub/substrate-node-template/issues/179
- https://github.com/paritytech/polkadot/issues/3482

Your use of that toolchain [seems correct from historical reports](https://stackoverflow.com/a/64585195/), but I believe this was remedied better with the use of the Substrate 2.0.1 patch release.

try:
```
cargo update -p sp-arithmetic
cargo update -p js-sys
cargo build --release
```
This _might_ solve it for you, I am working on a patch to get to 2.0.1: https://github.com/substrate-developer-hub/substrate-enterprise-sample/pull/88 (presently failing FYI)

**Comment by NukeManDan** [comment]
As an FYI: this repo is not actively maintained and _very_ stale. We are on substrate v3 and about to move to v4. Most development has moved to monthly releases.

**Comment by truedat101** [comment]
Agreed, its old and that was a concern I had.  But I thought for sure it would work in whatever last reported configuration was said to work.  Mainly interested in the design used in this repo .  I'll have a look at #74.

**Comment by truedat101** [comment]
Thanks will try out the suggestions.

**Comment by NukeManDan** [comment]
This error you have was from upstream compiler issues (a regression) and a yanked crate IIRC. So it did break builds (not just for us, and very frustrating to many substrate builders at the time)

**Comment by truedat101** [comment]
Hmm, no bueno on the cargo build --release step.

**Comment by saintfeng** [comment]
@truedat101 I compiled this repo on windows10 2 weeks ago. it runs well.

**Comment by truedat101** [comment]
Ok, I may switch to Windows or Linux to get through this evaluation.

**Comment by truedat101** [comment]
Going to retry this on Linux since that is available to me.

**Comment by NukeManDan** [comment]
on linux or wsl2, follow the directions: https://substrate.dev/docs/en/knowledgebase/getting-started/#ubuntudebian and setup your rust env (next section there)

**Comment by truedat101** [comment]
Not sure how this was fixed on OS X M1 mac.

**Comment by truedat101** [comment]
Not building on Ubuntu 16.04 either.  I'm assuming this is another untested configuration.  I'll move on.
